## Struct
---
le struct sono le stesse cose delle classi, ma non hanno un concetto di ereditarieta' e di polimorfismo.

Dal momento in cui definiamo una classe che diventa un tipo di dato e lo passiamo come parametro, essa viene data come indirizzo, mentre le struct vengono passate come valore. Se la struct sono da 40 - 60 byte allora nell'activation record vengono riservati altri 40 - 60 byte per la copia. Pero' quando esce dallo scope, esse vengono distrutte definitivamente. (Deep Copy)

```swift
enum Rank: Int {
	case ace = 1
	case two, three, four, five, six, seven, eight, nine, ten
	case jack, queen, king

	func simpleDescrip() -> String{
		switch self{
			case .ace:
				return "ace"
			case .jack:
				return "jack"
			case .queen:
				return "queen"
			case .king:
				return "king"
			default
				return String(self.rawValue)
		}
	}
}

// dal momento che dichiaro che ace = 1, gli altri vanno a scalare

let ace = Rank.ace
let RawValue = ace.rawValue
if let converted = Rank(rawValue:3){
	// controlla se esiste un valore in rank che sia 3
	let threeDesc = convertedRank.simpleDescription()
}

struct Card{
	var rank: Rank
	var suit: Suit
	func simpleDesc() -> String {
		return "The..."
	}
}

let threeOfSpades = Card(rank: .three, suit: .spades)
let desc = threeOfSpades.simpleDesc()
```
### Exceptions
---
Le eccezioni su swift fanno cagare a quanto pare.

```swift
enum PrinterError: Error{
	case outOfPaper
	case noToner
	case onFire 
}

func send(job: Int, toPrinter printerName: String) throws -> String {
	if printerName == 'Never has toner'{
		throw PrinterError.noToner
	}
	return "job sent"
}
```

In Swift c'e' il do catch che richiede anche il try:

```swift
do {
	let printeResponse = try send(job: 1440, toPrinter: "Gutenberg")
	print(printerResponse)
} catch PrinterError.onFire {
	print("literally on fire")
} catch let printerError as PrinterError {
	print("PrinterError: \(printerError)")
} catch {
	print(error)
}

// altro metodo piu' pulito

let printerSuccess = try? send(job: 1884, toPrinter: "Megainhaler")
let printerFailure = try? send(job: 1884, toPrinter: "Never has toner")
print("\(printerSuccess)")
print("\(printerFailure)")

// output di success: Optional("Job sent)
// per togliere Optional() bisogna mettere print("\(printerSuccess!)")
// output di failure: nil
// con questo metodo non si puo' vedere l'errore specifico

// in questo caso l'errore viene salvato nella variabile
```

dal momento in cui le strutture non possono essere estese e vengono passate per valore, mutating permette di modificare il corpo.